"""Stochastic simulation: fan charts generated by the model rather than bolted on.

simulate() is deterministic, so bands.py currently attaches uncertainty afterwards
from the historical error distribution, with hand-set scale factors:

    scale = {'gyy': {2026: 0.35}, 'cpi': {2026: 0.3}, 'u': {2026: 0.5}, 'i': {}}
    f = scale[v].get(y, 1.0) * (0.8 if v == 'gyy' and y > 2026 else 1.0)

Those factors are compensating for the missing simulation. Drawing correlated
shocks from the estimated residual covariance and running many paths produces the
distribution directly, and yields things the bolted-on version cannot:
joint scenarios, and probability statements such as P(CPI > 3% in 2027Q4).

    python stoch.py [N]
"""
import sys, json
import numpy as np, pandas as pd
from m2 import *

EQ = ['pc', 'is', 'ok', 'tr']   # equations that get a shock

def resid_cov(m, d):
    """Contemporaneous covariance of the four equations' residuals, on common quarters."""
    r = pd.DataFrame({k: m[k].resid for k in EQ}).dropna()
    return r.cov().values, list(r.columns), len(r)

def simulate_shocked(m, d, H, lo=None, lfx=None, lhe=None, shocks=None):
    """simulate() with an additive shock per equation per quarter.

    shocks: (H, 4) array ordered as EQ. The Phillips-curve and IS shocks enter through
    the existing add-factor channels; the Okun and Taylor shocks are applied directly.
    """
    T = d.index[-1]; idx = pd.period_range(T + 1, T + H, freq='Q')
    e = pd.concat([d, pd.DataFrame(index=idx)])
    for c in ['rstar', 'ustar', 'gpot']: e[c] = e[c].ffill()
    e.loc[idx, 'lo']  = d.lo.iloc[-1]  if lo  is None else lo
    e.loc[idx, 'lfx'] = d.lfx.iloc[-1] if lfx is None else lfx
    e.loc[idx, 'lhe'] = d.lhe.iloc[-1] if lhe is None else lhe
    e['doil'] = e.lo - L(e.lo, 4); e['dfx'] = e.lfx - L(e.lfx, 4)
    e['qo'] = e.lo.diff(); e['qfx'] = e.lfx.diff(); e['qhe'] = e.lhe.diff()
    seas = (d.lp.diff() - d.dp).groupby(d.sq).mean()
    pc, is_, tr, ok = m['pc'].params, m['is'].params, m['tr'].params, m['ok'].params
    S = np.zeros((H, len(EQ))) if shocks is None else shocks
    for j, p in enumerate(idx):
        s_pc, s_is, s_ok, s_tr = S[j]
        gap = (is_.gap1 * e.gap.shift(1)[p] + is_.gap2 * e.gap.shift(2)[p]
               + RG * (e.i - e.cpi - e.rstar).shift(2)[p] + OILD * e.doil.shift(1)[p] + s_is)
        e.loc[p, 'gap'] = gap
        x = pcX(e).loc[p]
        dp = 0.5 + (pc * x[pc.index]).sum() + s_pc
        e.loc[p, 'dp'] = dp; e.loc[p, 'lp'] = e.lp.shift(1)[p] + dp + seas[p.quarter]
        e.loc[p, 'cpi'] = (np.exp((e.lp[p] - e.lp.shift(4)[p]) / 100) - 1) * 100
        e.loc[p, 'g'] = e.gpot[p] + gap - e.gap.shift(1)[p]
        du = (ok.du1 * (e.u.shift(1)[p] - e.u.shift(2)[p]) + ok.gg * (e.g[p] - e.gpot[p])
              + ok.gg1 * (e.g.shift(1)[p] - e.gpot.shift(1)[p]) + s_ok)
        e.loc[p, 'u'] = e.u.shift(1)[p] + du
        i = tr.i1 * e.i.shift(1)[p] + tr.pi * e.cpi[p] + tr.gap * gap + tr.rstar * e.rstar[p] + tr.const + s_tr
        e.loc[p, 'i'] = max(i, 0.1)
    return e

def run(N=2000, H=18, seed=20260924, lo=None, lfx=None, lhe=None):
    d = prep(RAW); m = fit(d)
    C, order, n = resid_cov(m, d)
    rng = np.random.default_rng(seed)
    T = d.index[-1]; idx = pd.period_range(T + 1, T + H, freq='Q')
    keep = {v: np.empty((N, H)) for v in ['g', 'cpi', 'u', 'i']}
    for k in range(N):
        S = rng.multivariate_normal(np.zeros(len(EQ)), C, size=H)
        e = simulate_shocked(m, d, H, lo, lfx, lhe, S)
        for v in keep: keep[v][k] = e.loc[idx, v].values
    return idx, keep, C, order, n

def summarise(idx, keep, qs=(5, 25, 50, 75, 95)):
    out = {}
    for v, a in keep.items():
        out[v] = {'p%d' % q: np.percentile(a, q, axis=0).round(3).tolist() for q in qs}
    out['_q'] = [str(p) for p in idx]
    return out

def _cli_diag():
    N = int(sys.argv[1]) if len(sys.argv) > 1 and sys.argv[1].isdigit() else 2000
    print('drawing %d paths from the estimated residual covariance...' % N)
    idx, keep, C, order, n = run(N)
    print('\nresidual correlation (%d common quarters):' % n)
    D = np.sqrt(np.diag(C)); R = C / np.outer(D, D)
    print('        ' + ''.join('%8s' % o for o in order))
    for i, o in enumerate(order):
        print('%-8s' % o + ''.join('%8.2f' % R[i, j] for j in range(len(order))))
    print('\nsigma: ' + ', '.join('%s %.3f' % (o, D[i]) for i, o in enumerate(order)))
    S = summarise(idx, keep)
    print('\nCPI fan, model-generated (annual rate, %%):')
    print('%-8s %7s %7s %7s %7s %7s' % ('quarter', 'p5', 'p25', 'p50', 'p75', 'p95'))
    for j, q in enumerate(S['_q']):
        if j % 3 == 0 or j == len(S['_q']) - 1:
            print('%-8s %7.2f %7.2f %7.2f %7.2f %7.2f' % (q, *[S['cpi']['p%d' % p][j] for p in (5, 25, 50, 75, 95)]))
    tgt = [j for j, q in enumerate(S['_q']) if q == '2027Q4']
    if tgt:
        j = tgt[0]; a = keep['cpi'][:, j]
        print('\nProbability statements for 2027Q4, impossible without simulation:')
        for thr in (2.0, 2.5, 3.0, 4.0):
            print('  P(CPI > %.1f%%) = %4.1f%%' % (thr, (a > thr).mean() * 100))
        print('  P(Bank Rate > 4%%)  = %4.1f%%' % ((keep['i'][:, j] > 4).mean() * 100))
        print('  P(CPI > 3%% and Bank Rate > 4%%) = %4.1f%%  (joint, needs the same draws)'
              % (((a > 3) & (keep['i'][:, j] > 4)).mean() * 100))
    json.dump(S, open('stoch_bands.json', 'w'))
    print('\nwritten to stoch_bands.json')

# ---------------------------------------------------------------------------
# Annual bands for model_export.json, replacing bands.py
# ---------------------------------------------------------------------------

YRS = [2026, 2027, 2028, 2029, 2030]

def _annual(e, ymeanG0):
    """The four headline annuals, computed exactly as fc.py does."""
    lvl = (1 + e.g / 100).cumprod()
    base = {2026: ymeanG0}
    out = {'gdp': [], 'cpi': [], 'unemp': [], 'rate': []}
    for y in YRS:
        prev = base.get(y) if y in base else lvl[e.index.year == y - 1].mean()
        out['gdp'].append(float((lvl[e.index.year == y].mean() / prev - 1) * 100))
        out['cpi'].append(float(e.cpi[e.index.year == y].mean()))
        out['unemp'].append(float(e.u[e.index.year == y].mean()))
        out['rate'].append(float(e.i[pd.Period('%dQ4' % y)]))
    return out

def bands(N=2000, seed=20260924, export='model_export.json'):
    """Fan charts from the simulated distribution of the ANNUAL aggregates.

    bands.py took quantiles of quarterly forecast errors and averaged them across the
    horizons falling in each year. That is not the quantile of the annual average, and it
    cannot represent a part-actual year, which is what the scale factors
    ({'gyy': {2026: 0.35}, 'cpi': {2026: 0.3}, 'u': {2026: 0.5}} and the 0.8 on growth)
    were correcting by hand.

    Computing each path's annual aggregate and then taking quantiles handles both: 2026 is
    narrow automatically because its first two quarters are actual and carry no shock.
    """
    m_exp = json.load(open(export))
    st = m_exp['state']; ymeanG0 = st['ymeanG0']
    lo  = np.array(st['path']['lo']);  lfx = np.array(st['path']['lfx']); lhe = np.array(st['path']['lhe'])
    H   = len(lo)
    idx0 = pd.Period(st['path']['q'][0], 'Q')
    af, gaf = st['af'], st['gaf']

    d = prep(RAW); m = fit(d)
    C, order, n = resid_cov(m, d)
    rng = np.random.default_rng(seed)
    draws = {k: [] for k in ['gdp', 'cpi', 'unemp', 'rate']}
    for _ in range(N):
        S = rng.multivariate_normal(np.zeros(len(EQ)), C, size=H)
        S[0, order.index('pc')] += af          # keep the nowcast anchoring of the first quarter
        S[0, order.index('is')] += gaf
        e = simulate_shocked(m, d, H, lo, lfx, lhe, S)
        a = _annual(e, ymeanG0)
        for k in draws: draws[k].append(a[k])
    out = {}
    for k, v in draws.items():
        A = np.array(v)                         # (N, 5)
        med = np.median(A, axis=0)
        out[k] = {'p%02d' % q: np.round(np.percentile(A, q, axis=0) - med, 3).tolist()
                  for q in (5, 25, 75, 95)}
    m_exp['bands'] = out
    m_exp['bands_method'] = {'source': 'stoch.py', 'draws': N, 'seed': seed,
                             'basis': 'quantiles of simulated annual aggregates, as deviations from the simulated median'}
    json.dump(m_exp, open(export, 'w'))
    return out, draws


if __name__ == '__main__':
    nums = [a for a in sys.argv[1:] if a.isdigit()]
    N = int(nums[0]) if nums else 2000
    if '--bands' in sys.argv:
        print('generating bands from %d simulated paths...' % N)
        out, draws = bands(N)
        hdr = '%-7s %8s %8s %8s %8s   (deviations from the simulated median)'
        print(hdr % ('', 'p05', 'p25', 'p75', 'p95'))
        for k in ['gdp', 'cpi', 'unemp', 'rate']:
            for j, y in enumerate(YRS):
                print('%-7s %8.2f %8.2f %8.2f %8.2f   %d' % (
                    k if j == 0 else '', out[k]['p05'][j], out[k]['p25'][j],
                    out[k]['p75'][j], out[k]['p95'][j], y))
            print()
        print('written to model_export.json[bands]')
    else:
        _cli_diag()
